version : '3.7'

services:

  trading_signals:
    image: trading_signals
    container_name: trading_signals
    restart: always
    volumes:
    - ./:/mining/

  flask:
    image: flask
    container_name: flask
    restart: always
    ports:
      - 5001:5001
    volumes:
    - ./:/mining/
