version : '3.7'

services:

  trading_signals:
    image: trading_signals
    container_name: trading_signals
    restart: always
    volumes:
    - ./:/mining/
    networks: 
      - network1

  flask:
    image: flask
    container_name: flask
    restart: always
    ports:
      - 5001:5001
    volumes:
    - ./:/mining/
    networks: 
      - network1

  apache:
    image: ownphp
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./:/mining/
    networks: 
      - network1


networks:
  network1:
    name: my-pre-existing-network
    external: true