FROM python:3

ENV TERM=xterm

# Python Requirements

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /mining

CMD [ "python", "-u", "/mining/Python/prediction2.py" ]
